### ISSUE TITLE
Improve feedback on failure

### ISSUE THREAD

**Issue by gingermusketeer** [digitalsadhu/envoodoo#2]
https://github.com/digitalsadhu/envoodoo/blob/master/index.js#L17

The user will not know if the env has been loaded by returning false. This is assuming that envoodoo is invoked without assigning the result and checking it.

Perhaps a flag could be passed in signifying that a silent failure is desired. Not sure if it is needed though

**Comment by rbudiharso** [comment]
On version 2.1.0 you can listen to error using the asynchronous style
```javascript 
envoodoo('file.env', function(err)  {
  if (err) {
    // throw maybe?
 } 
  // environment variables is loaded
});
```
Closing this, feel free to reopen if there's anything wrong 😁
